### ISSUE TITLE
sail's chrome extension performance error

### ISSUE THREAD

**Issue by yhyddr** [cdr/sail#214] opened 2019-06-10 11:47 UTC
when visit a GitHub repository that may use sail
if you visit another page and back to repo page. There are one more `open in sail` button on it.
like this
![image](https://user-images.githubusercontent.com/32089134/59193532-99145280-8bb8-11e9-85d6-1bfbab9383b4.png)

**Comment by deansheather** [comment] 2019-06-11 07:08
Duplicate of #157.

**Closed by deansheather** 2019-06-11 07:08 UTC
